p = float(input("Enter the amount deposited: "))
r = float(0.04)
first_Year = int(1)
second_Year = int(2)
third_Year = int(3)
#A = P(1+r/n) * pow(time)
amount_one = p * (pow((1 + r / 100), first_Year))
amount_two = p * (pow((1 + r / 100), second_Year))
amount_three = p * (pow((1 + r / 100), third_Year))
print("The amount in your savings after one year is " + str(round(amount_one, 2))) 
print("The amount in your savings after two years is " + str(round(amount_two, 2)))
print("The amount in your savings after three years is " + str(round(amount_three, 2)))